version: '3.8'

services:
  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"   # Jaeger thrift compact protocol
      - "6832:6832/udp"   # Jaeger thrift binary protocol
      - "5778:5778"       # Jaeger configs
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "14250:14250"     # Model handler
      - "14268:14268"     # Jaeger HTTP thrift collector
      - "14269:14269"     # Health check
      - "9411:9411"       # Zipkin compatible endpoint
    networks:
      - gomicrokit-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:16686"]
      interval: 5s
      timeout: 3s
      retries: 3

  # etcd for service discovery and registration
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    command: 
      - /usr/local/bin/etcd
      - --name=etcd
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - gomicrokit-net
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 3s
      retries: 3