# .github/workflows/benchmark.yml
name: Benchmark

on:
  push:
    branches: [ main ]

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run benchmarks
        run: |
          mkdir -p dev/bench
          go test -bench=. -benchmem ./... | tee benchmark-result.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: benchmark-result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          # Use GitHub's default configuration for gh-pages
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          skip-fetch-gh-pages: false
          # Set this to true to create the branch if it doesn't exist
          auto-push-gh-pages: true