# .github/workflows/benchmark.yml
name: Benchmark

on:
  push:
    branches: [ main ]

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Create gh-pages branch if not exists
        run: |
          git fetch origin || true
          if ! git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout -
          fi

      - name: Run benchmarks
        run: |
          mkdir -p dev/bench
          go test -bench=. -benchmem ./... | tee benchmark-result.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: benchmark-result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true