# .github/workflows/benchmark.yml
name: Benchmark

on:
  push:
    branches: [ main ]

jobs:
  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run benchmarks
        run: |
          # Create the output directory if it doesn't exist
          mkdir -p dev/bench
          
          # Run the benchmarks and save the output to a file
          go test -bench=. -benchmem ./... | tee benchmark-result.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: benchmark-result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench